### ISSUE TITLE
Prozessplanung (Scrum, Kanban etc.)

### ISSUE THREAD

**Issue by maxammann** [ehrenamtskarte/planning#3]
* Wie kommen wir von unseren Requirements zu Issues? Meetings?
* Wie sieht der Prozess aus?

**Comment by maxammann** [comment]
# Meetings:
* [x] Reviews - Vorstellung der entwickelten Features & Diskussion
  * Eingeladen sind Stackholder: PuLi Betreuer, Sozialministerium, Externe
  * Ca. 1 mal pro Monat
* [x] Retro - Teamretro
  * 2 mal im Semester
* [x] Weeklys
* [ ] Groomings

# Allgemeines: 
* Es sollte einen PO aka. Issuemaster geben der die Issues aktuell hält und eine mindestanzahl von Issues bereithält, die bearbeitet werden können
* Es soll Code-Reviews für Issues geben (min 1 Approval)

**Comment by elKei24** [comment]
Moved this to the [wiki](../wiki/Process)
